name: homework-5-git-basics
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=21.2.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - iniconfig=1.1.1
  - libcxx=12.0.1
  - libffi=3.3
  - more-itertools=8.8.0
  - ncurses=6.2
  - openssl=1.1.1k
  - packaging=21.0
  - pip=21.1.3
  - pluggy=0.13.1
  - py=1.10.0
  - pyparsing=2.4.7
  - pytest=6.2.4
  - python=3.9.6
  - python_abi=3.9
  - readline=8.1
  - setuptools=49.6.0
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
